apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: empirical-tyrannosaurus-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:e01a68caebe6f85df1c8443fd632a969c076473e@sha256:827fae1cde45c7f6afe56dd0f1a715b955feecfa67f7e99a2b9c4e3a1356e75e
        name: container-image  
